language: node_js
sudo: required
services:
  - docker
node_js:
  - "11.0.0"
jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run test
    - stage: "build and deploy"
      script:
        - docker build --force-rm=true -t $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT .
      after_success:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
        - echo $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT
        - docker push $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT ;